---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop l-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm l-container
      ignore_errors: yes

    - name: remove ansible-image
      command: docker rmi ansible-img
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t ansible-img .
      
    - name: create tag to image 
      command: docker tag  ansible-img  hadijaber97/ansible-repo

    - name: run container
      command: docker run -d --name ansible-container  -p 5000:80 hadijaber97/ansible-repo

